/* !! DON'T MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING !! */
#pragma once

/* Includes generic iTunes logo for any songs that dont have a corresponding album asset */
#define DEFAULT_DISCORD_APPLICATION_ID      "1095131480147103744"
#define DEFAULT_DISCORD_APP_IMAGE_KEY       "small - icon"

typedef struct DiscordAppAlbumAssets
{
	 const char* ApplicationId;
	 const char* AlbumNames[300];
};

const DiscordAppAlbumAssets g_DiscordAppsAlbums[2] = {
    { "1252014407005896745", {
        "4:44",
        "Bad Boy's 10th Anniversary... The Hits",
        "Greatest Hits",
        "Ready to Die - The Remaster",
        "Life After Death (Remastered Edition)",
        "Notorious (Music from and Inspired By the Original Motion Picture) [Deluxe Version]",
        "Hard Core",
        "Project: Funk Da World",
        "Hip Hop Workout",
        "2001",
        "Kingdom Come",
        "The Hits Collection, Vol. One (Deluxe Edition)",
        "All Eyez On Me (Remastered)",
        "Death Certificate",
        "The Music of Grand Theft Auto V",
        "Not Tonight - EP",
        "Rocket League x Monstercat Vol. 1",
        "The Hate U Give (Original Motion Picture Soundtrack)",
        "Dex Meets Dexter",
        "Black Panther The Album Music From And Inspired By",
        "The Best of DJ Quik - Da Finale",
        "?",
        "E. 1999 Eternal",
        "Evolution of Gospel",
        "Love Behind the Melody",
        "Tamia",
        "Return to the 36 Chambers",
        "The Black Album",
        "Original Musiquarium",
        "The 12\" Collection And More (Funk Essentials)",
        "Voicenotes",
        "Born Again",
        "Long Live The Kane",
        "Watch the Throne",
        "Anarchy",
        "Don't Be Cruel",
        "It's Real",
        "Just a Dream - Single",
        "Thank Me Later",
        "The Time Machine (Original Motion Picture Soundtrack)",
        "twenty one pilots",
        "Vessel",
        "16*29",
        "Regional At Best",
        "STAY DANGEROUS",
        "Sunflower - Single",
        "The Big Bang",
        "Hozier (Bonus Track Version)",
        "F.A.M.E. (Expanded Edition)",
        "#SantanaWorld (+)",
        "Winnebago (feat. Quinn XCII & Daniel Wilson) - Single",
        "The Black Parade",
        "A Fever You Can't Sweat Out",
        "Habits (Bonus Track Version)",
        "Redrum - Single",
        "Losing You - Single",
        "Best Friend - Single",
        "Leave Me Alone - Single",
        "Claudia - Single",
        "The Drug In Me Is You",
        "Minecraft - Volume Beta",
        "In Utero (20th Anniversary Edition)",
        "I Love You.",
        "Christmas Card",
        "Roy Pablo - EP",
        "Soy Pablo - EP",
        "LIFE'S A TRIP",
        "The Look - EP",
        "Apricot Princess",
        "All Eyez On Me",
        "W2Leezy - Single",
        "Loving Is Easy (feat. Benny Sings) - Single",
        "Eternal Atake (Unreleased)",
        "Eternal Atake",
        "Die Lit",
        "Playboi Carti",
        "Nuthin' 2 Prove",
        "Bcos U Will Never B Free",
        "Weezer (Green Album)",
        "Pony",
        "The Blueprint",
        "The Best of Little Anthony & The Imperials",
        "wannabewithu",
        "Chanel - Single",
        "Too Weird to Live, Too Rare to Die!",
        "Death of a Bachelor",
        "Chiquito - EP",
        "Lil Uzi Vert Vs. The World",
        "Luv Is Rage 2",
        "Coloring Book",
        "Drip Season 2",
        "7 - EP",
        "Starboy",
        "WLR",
        "Drip Harder",
        "Strawberry Letter 23 / The Very Best of the Brothers Johnson (Remastered)",
        "Lil Boat 2",
        "Live From Space",
        "Macadelic",
        "On And On And Beyond - EP",
        "Pose (feat. Lil Uzi Vert) - Single",
        "Please Excuse Me For Being Antisocial",
        "Luv Is Rage 2 (Deluxe)",
        "Luv Is Rage",
        "Broccoli (feat. Lil Yachty) - Single",
        "Watching Movies with the Sound Off",
        "How Will You Know If You Never Try",
        "My Turn",
        "ASTROWORLD",
        "So Much Fun",
        "KIRK",
        "HIGHEST IN THE ROOM - Single",
        "Harder Than Ever",
        "Eternal Atake (Deluxe) - LUV vs. The World 2",
        "Swimming",
        "Lifestyle (feat. Young Thug & Rich Homie Quan) - Single",
        "Death Race for Love",
        "Let Me Know (I Wonder Why Freestyle) - Single",
        "Quality Control: Control The Streets, Vol. 2",
        "Baby - Single",
        "Quality Control: Control the Streets, Vol. 1",
        "MEMORIES DON'T DIE",
        "@ MEH - Single",
        "2014 Forest Hills Drive",
        "The Perfect LUV Tape",
        "Heaven Or Hell",
        "Love Me // Leave Me",
        "Rodeo",
        "American Gangster",
        "The Fame",
        "The Blueprint 3",
        "Goodbye & Good Riddance",
        "Baby on Baby",
        "The Marshall Mathers LP",
        "DAMN.",
        "untitled unmastered.",
        "To Pimp a Butterfly",
        "True 2 Myself",
        "Die a Legend",
        "Huncho Jack, Jack Huncho",
        "Birds in the Trap Sing McKnight",
        "Birds In The Trap Sing McKnight",
        "Revenge of the Dreamers III: Director's Cut",
        "Dark Lane Demo Tapes",
        "The New Toronto 3",
        "Meet the Woo",
        "BLAME IT ON BABY",
        "The Life of Pi'erre 4",
        "Limbus, Pt. 2",
        "Realer",
        "Turks (feat. Travis Scott) - Single",
        "Certified Hitmaker",
        "Cry Baby (Deluxe Edition)",
        "So Much Fun (Deluxe)",
        "High Off Life",
        "Best Day Ever (5th Anniversary Remastered Edition)",
        "Blue Slide Park",
        "NOT ALL HEROES WEAR CAPES",
        "AT.LONG.LAST.A$AP",
        "FATHER OF 4",
        "The Last Rocket",
        "Fan of a Fan the Album (Expanded Edition)",
        "...And Then There Was X",
        "Nightcall",
        "KOD",
        "Alone - Single",
        "Jungle Rules",
        "Trip",
        "T R A P S O U L",
        "When It's Dark Out",
        "DS2 (Deluxe)",
        "JESUS IS KING",
        "The Life of Pablo",
        "In My Lifetime, Vol. 1",
        "Watch the Throne (Deluxe)",
        "you and me again - EP",
        "Clarity - Single",
        "Nothing Happens",
        "Immunity",
        "diary 001 - EP",
        "Sunday - Single",
        "Marlboro Nights - Single",
        "Won't Stop / All For You - Single",
        "Big Mood - Single",
        "I Ur Boy",
        "? (Deluxe)",
        "Paramore",
        "Van Weezer",
        "Ugly is Beautiful",
        "Enemy - Single",
        "Welcome To LA - Single",
        "Smile (feat. Sophie Meiers & Sophie Meiers) - Single",
        "Goodie Bag - Single",
        "Window - Single",
        "After Noon - Single",
        "17",
        "Three Cheers for Sweet Revenge",
        "Lo Que Siento - Single",
        "Bossa No Sé (feat. Jean Carter) - Single",
        "Drown - Single",
        "Culture",
        "WUNNA",
        "Dying to Live",
        "Need It (feat. YoungBoy Never Broke Again) - Single",
        "Lil Boat 3",
        "A Love Letter To You 4 (Deluxe)",
        "!",
        "Chill Bill (feat. J. Davi$ & Spooks) - Single",
        "RECKLESS",
        "Only in Dreams",
        "Hatchback - Single",
        "Slime Language",
        "SUPER SLIMEY",
        "Future & Juice WRLD Present... WRLD ON DRUGS",
        "Watch (feat. Lil Uzi Vert & Kanye West) - Single",
        "Peso - Single",
        "A$AP Forever (feat. Moby) - Single",
        "Mamacita (feat. Rich Homie Quan & Young Thug) - Single",
        "Come & Go - Single",
        "My Turn (Deluxe)",
        "Capital Punishment",
        "Don't Play (feat. The 1975 & Big Sean) - Single",
        "Upper Echelon (feat. T.I. & 2 Chainz) - Single",
        "Get It (feat. Tay-K) - Single",
        "Championships",
        "L.A. Originals (Original Motion Picture Soundtrack)",
        "Finally Rich (Deluxe Version)",
        "Flower Boy",
        "Wolf",
        "My Beautiful Dark Twisted Fantasy",
        "Man on the Moon: The End of Day (Deluxe)",
        "Through the Years: The Best of the Fray",
        "WUNNA (Deluxe)",
        "Barter 6",
        "Dream State - Single",
        "Drip or Drown 2",
        "JEFFERY",
        "FRANCHISE (feat. Young Thug & M.I.A.) - Single",
        "Goodbye Yellow Brick Road",
        "SAVAGE MODE II",
        "Armed and Dangerous - Single",
        "FRANCHISE (REMIX) [feat. Future, Young Thug & M.I.A.] - Single",
        "Poolside",
        "This Is the Sea (Deluxe Version)",
        "In Trap We Trust, Vol. 3",
        "Synth Pop",
        "Play & Play: B Sides",
        "The Very Best of Daryl Hall & John Oates",
        "Party In the U.S.A. - Single",
        "Tha Carter IV (Complete Edition)",
        "Whole Lotta Red",
        "Touch",
        "Sundress - Single",
        "Vol. 3... Life and Times of S. Carter",
        "Seal: Best 1991-2004 (Deluxe Version)",
        "The Album",
        "TESTING",
        "Superclean, Vol. I - EP",
        "Queen of the Clouds",
        "Goblin (Deluxe Edition)",
        "Goblin",
        "Some Rap Songs",
        "Cherry Bomb",
        "Currents",
        "You Know You Like It - Single",
        "Justified",
        "LONG.LIVE.A$AP (Deluxe Version)",
        "Hot Pink",
        "Czarface Meets Metal Face",
        "LONG.LIVE.A$AP (Deluxe Edition)",
        "Ironman",
        "Starting Over (Deluxe Edition)",
        "Cozy Tapes, Vol. 1: Friends",
        "The Ultimate Collection (Remastered)",
        "The War Report",
        "The Family Jewels",
        "Yours Truly",
        "Electra Heart (Deluxe Version)",
        "Word Up!",
        "FROOT",
        "Dusk - Single",
        "Bad Boy - Single",
        "Ancient Dreams In A Modern Land",
        "La Roux (Bonus Track Version)",
        "Top Five (Music From and Inspired By the Motion Picture)",
        "Born to Die",
        "Ultraviolence (Deluxe)",
        "Paradise",
        "The Truth",
        "Legend – The Best of Bob Marley & The Wailers (2002 Edition)",
        "The Essential Billy Joel",
        "Sings Smooth Jazz Classics",
        "Vices & Virtues (Deluxe Edition)",
        "Magna Carta... Holy Grail",
        "Aftercluv Dancelab the Drop, Vol. 1",
        "U218 Singles",
        "Harry Styles",
        "The Best of Andrea Bocelli: Vivere",
        "Up All Night (Deluxe Version)",
        "INDUSTRY BABY - Single"
    } },
    { "1252387378321162360", {
        "Come On Eileen / Dubious - Single",
        "Loose",
        "Thriller",
        "The Fray",
        "Electric Ladyland",
        "LA Thunder Covers Led Zeppelin Collection, Vol. 2",
        "Get Lifted",
        "Paper Trail",
        "Fine Line",
        "Born To Die - The Paradise Edition",
        "Norman F*****g Rockwell!",
        "Waking Up",
        "Cars (Original Motion Picture Soundtrack)",
        "1989",
        "Red",
        "My Everything",
        "Dangerous Woman",
        "Beauty Behind the Madness",
        "7/27 (Deluxe)",
        "Snapshot",
        "Honeymoon",
        "Get Rich or Die Tryin' (Bonus Track Version)",
        "K.I.D.S. (Deluxe)",
        "1000 Forms of Fear",
        "The Fame Monster (Deluxe Edition)",
        "Teenage Dream: The Complete Confection",
        "Heartbeat City",
        "The Lady Killer (Deluxe Version)",
        "A Rush of Blood to the Head",
        "My Head Is an Animal",
        "NO STYLIST",
        "Global Warming: Meltdown (Deluxe Version)",
        "Midnight Memories (Deluxe Edition)",
        "Toto IV",
        "Crystal Castles",
        "if looks could kill - Single",
        "Lyfë",
        "Back from the Dead",
        "Back from the Dead 2",
        "MURDAMAN! (feat. Chief Keef) - Single",
        "25",
        "21",
        "2 Alivë",
        "SlimeBall 2",
        "Tell Em - Single",
        "When The Sun Goes Down",
        "...Baby One More Time (Deluxe Version)",
        "Some Nights",
        "Pink Tape",
        "Memories",
        "Molly World",
        "Ancient Dreams In A Modern Land (Deluxe Edition)",
        "Suicide Squad: The Album",
        "Diamond Eyes (Deluxe Edition)",
        "Seminole Wind",
        "SHAMELESS $UICIDE - EP",
        "Antarctica - Single",
        "$Outh $Ide $Uicide - EP",
        "I No Longer Fear the Razor Guarding My Heel (II) - Single",
        "Avalon - Single",
        "Long Term Effects of SUFFERING",
        "Gray/Grey",
        "7th or St. Tammany",
        "KILL YOURSELF Part XII: The Dark Glacier Saga - Single",
        "Stop Staring at the Shadows",
        "I No Longer Fear the Razor Guarding My Heel - Single",
        "DIRTIESTNASTIEST$UICIDE",
        "Paris - Single",
        "My Liver Will Handle What My Heart Can't",
        "Eternal Grey",
        "Kill Yourself (Part IV) - Single",
        "Sing Me a Lullaby, My Sweet Temptation",
        "I No Longer Fear The Razor Guarding My Heel (V) - Single",
        "Five Five",
        "The South Got Something to Say",
        "Blood Was Never Thick As Water",
        "THE PLAYA$ MANUAL",
        "Son of Serpentine",
        "Drop out of School 2 - EP",
        "Drop Out of School",
        "Black $uicide - EP",
        "I No Longer Fear the Razor Guarding My Heel (III) - Single",
        "YUNGDEATHLILLIFE",
        "Grey Sheep II",
        "KILL YOURSELF Part XIII: The Atlantis Saga - Single",
        "Dark Side of the Clouds",
        "Meet Me Where the River Turns Grey",
        "KILL YOURSELF Part I: The $uicide Saga - EP",
        "YIN YANG TAPES: Summer Season (1989-1990) - EP",
        "I Want to Die in New Orleans",
        "KILL YOURSELF Part XIX: The Deep End Saga - Single",
        "Live Fast, Die Whenever - EP",
        "Koi No Yokan",
        "Saturday Night Wrist (Bonus Track Version)",
        "Around the Fur",
        "Pure Heroine",
        "Drew's Famous Sports Party Music",
        "Keep On Movin'",
        "Blurryface",
        "Out of Business",
        "Tomahawk Technique",
        "Reasonable Doubt",
        "MTV Unplugged: Jay-Z (Live)",
        "Let's Fall in Love for the Night - Single",
        "New Girl - Single",
        "Blood Harmony (Deluxe)",
        "BALLADS 1",
        "Sincerely, Tokyo",
        "The GloFiles Pt. 4",
        "Miss the Rage - Single",
        "Illmatic",
        "A Decade of Steely Dan (Remastered)",
        "Hot Vodka 1",
        "Narcissistic Cannibal - Single",
        "I Can't Handle Change - EP",
        "Melophobia",
        "Because the Internet",
        "Songs of Innocence",
        "Born to Die - The Paradise Edition",
        "Skyfall - Single",
        "The Blueprint 2: The Gift & the Curse"
    } }
};